# Spam Classification

In [2]:
import requests
import tarfile

import pandas as pd
from sklearn.model_selection import train_test_split

from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.pipeline import make_pipeline


from bs4 import BeautifulSoup
from pathlib import Path

- Download and unzip dataset files from `https://spamassassin.apache.org/old/publiccorpus/`

In [3]:
BASE_URL = "https://spamassassin.apache.org/old/publiccorpus/"
DOWNLOAD_DIR = Path("../datasets/spamassassin_corpus")
DOWNLOAD_DIR.mkdir(exist_ok=True)

In [4]:
# Get directory listing
response = requests.get(BASE_URL)
response.raise_for_status()
soup = BeautifulSoup(response.content, "html.parser")

# Download every .tar.bz2 file
for link in soup.find_all("a"):
    href = link.get("href")
    if href and href.endswith(".tar.bz2"):
        url = BASE_URL + href
        out_file = DOWNLOAD_DIR / href

        print(f"Downloading {href}...")

        with requests.get(url, stream=True) as r:
            r.raise_for_status()
            with open(out_file, "wb") as f:
                for chunk in r.iter_content(chunk_size=8192):
                    if chunk:
                        f.write(chunk)

print("Done.")

Downloading 20021010_easy_ham.tar.bz2...
Downloading 20021010_hard_ham.tar.bz2...
Downloading 20021010_spam.tar.bz2...
Downloading 20030228_easy_ham.tar.bz2...
Downloading 20030228_easy_ham_2.tar.bz2...
Downloading 20030228_hard_ham.tar.bz2...
Downloading 20030228_spam.tar.bz2...
Downloading 20030228_spam_2.tar.bz2...
Downloading 20050311_spam_2.tar.bz2...
Done.

In [6]:
for archive in DOWNLOAD_DIR.glob("*.tar.bz2"):
    extract_dir = DOWNLOAD_DIR / archive.stem.replace(".tar", "")
    extract_dir.mkdir(exist_ok=True)

    print(f"Extracting {archive.name}...")
    with tarfile.open(archive, "r:bz2") as tar:
        tar.extractall(extract_dir)

print("Extraction complete.")

Extracting 20030228_hard_ham.tar.bz2...
Extracting 20021010_hard_ham.tar.bz2...
Extracting 20030228_spam_2.tar.bz2...
Extracting 20030228_easy_ham_2.tar.bz2...
Extracting 20030228_spam.tar.bz2...
Extracting 20030228_easy_ham.tar.bz2...
Extracting 20021010_spam.tar.bz2...
Extracting 20021010_easy_ham.tar.bz2...
Extracting 20050311_spam_2.tar.bz2...
Extraction complete.

In [4]:
rows = []

def combine_associated_files(folder_path, label):
    for file in folder_path.iterdir():
        if file.is_file():
            try:
                text = file.read_text(errors="ignore")
                rows.append({
                    "text": text,
                    "label": label
                })
            except Exception:
                pass
    else:
        for subfolder in folder_path.iterdir():
            if subfolder.is_dir():
                combine_associated_files(subfolder, label)

for folder_path in DOWNLOAD_DIR.iterdir():
    if not folder_path.is_dir():
        continue

    folder_name = folder_path.name.lower()
    
   

    if "ham" in folder_name:
        label = 0
    elif "spam" in folder_name:
        label = 1
    else:
        continue
    
    print(f"Processing folder: {folder_name} is labeled as {label}")

    combine_associated_files(folder_path, label)
            

df = pd.DataFrame(rows)

df.head()

Processing folder: 20030228_easy_ham_2 is labeled as 0
Processing folder: 20030228_hard_ham is labeled as 0
Processing folder: 20030228_spam is labeled as 1
Processing folder: 20030228_easy_ham is labeled as 0
Processing folder: 20030228_spam_2 is labeled as 1
Processing folder: 20021010_spam is labeled as 1
Processing folder: 20021010_hard_ham is labeled as 0
Processing folder: 20021010_easy_ham is labeled as 0
Processing folder: 20050311_spam_2 is labeled as 1

                                                text  label
0  From rpm-list-admin@freshrpms.net  Mon Jul 22 ...      0
1  From webmake-talk-admin@lists.sourceforge.net ...      0
2  From fork-admin@xent.com  Wed Aug 14 11:01:15 ...      0
3  From ilug-admin@linux.ie  Mon Jul 22 19:50:20 ...      0
4  From razor-users-admin@lists.sourceforge.net  ...      0

In [5]:
X = df["text"]
y = df["label"]

print(f"Total samples: {len(df)} Split into 8:2 train-test ratio.")

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

Total samples: 10751 Split into 8:2 train-test ratio.

In [6]:
vectorizer = TfidfVectorizer(stop_words="english")
X_train_vectorized = vectorizer.fit_transform(X_train)


X_train_vectorized.shape, y_train.shape

((8600, 182225), (8600,))

In [7]:
from sklearn.linear_model import LogisticRegression

log_ref = LogisticRegression()
log_ref.fit(X_train_vectorized, y_train)

LogisticRegression()

In [ ]:
from sklearn.metrics import classification_report

X_test_vectorized = vectorizer.transform(X_test)

y_test_pred = log_ref.predict(X_test_vectorized)

print(classification_report(y_test, y_test_pred, target_names=["Ham", "Spam"]))

              precision    recall  f1-score   support

         Ham       0.98      0.99      0.99      1391
        Spam       0.99      0.96      0.97       760

    accuracy                           0.98      2151
   macro avg       0.98      0.98      0.98      2151
weighted avg       0.98      0.98      0.98      2151

In [10]:
from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier(n_estimators=100, random_state=42)
rf_clf.fit(X_train_vectorized, y_train)

RandomForestClassifier(random_state=42)

In [11]:
y_test_pred = rf_clf.predict(X_test_vectorized)
print(classification_report(y_test, y_test_pred, target_names=["Ham", "Spam"]))

              precision    recall  f1-score   support

         Ham       0.99      1.00      0.99      1391
        Spam       0.99      0.99      0.99       760

    accuracy                           0.99      2151
   macro avg       0.99      0.99      0.99      2151
weighted avg       0.99      0.99      0.99      2151

In [18]:
# Retrieve built-in importances
feature_names = vectorizer.get_feature_names_out()


# Create a clean DataFrame mapped to feature names
feature_imp_df = pd.DataFrame({
    'Feature': feature_names,
    'Importance': rf_clf.feature_importances_
}).sort_values(by='Importance', ascending=False)

feature_imp_df.head(10)

          Feature  Importance
59596   beenthere    0.011062
156232     single    0.009618
123971  localhost    0.008213
164785         tr    0.007915
108082       href    0.007284
11834         127    0.006129
150034    request    0.006033
142351      plain    0.005816
179532       yyyy    0.005731
119425   keywords    0.005713

In [ ]:
y_test_pred = rf_clf.predict(X_test_vectorized)
print(classification_report(y_test, y_test_pred, target_names=["Ham", "Spam"]))